class Recipe {
  final String id;
  final String title;
  final List<String> ingredients;
  final String instructions;
  final int calories;
  final String cuisine;
  final List<String> dietary;
  final String meatType;
  final String mealType;
  final int preparationTime; // Added preparation time
  final int cookingTime; // Added cooking time
  final String imageUrl; // Added image URL
  final double rating; // Added rating
  final List<String> tags; // Added tags for categorizing recipes
  final bool isFavorite; // Added favorite status

  Recipe({
    required this.id,
    required this.title,
    required this.ingredients,
    required this.instructions,
    required this.calories,
    required this.cuisine,
    required this.dietary,
    required this.meatType,
    required this.mealType,
    required this.preparationTime,
    required this.cookingTime,
    required this.imageUrl,
    required this.rating,
    required this.tags,
    required this.isFavorite,
  });
}

List<Recipe> recipes = [
  // Existing recipes from 1 to 10
  Recipe(
    id: '1',
    title: 'Chicken Stir Fry',
    ingredients: ['Chicken', 'Bell Peppers', 'Soy Sauce', 'Garlic', 'Ginger'],
    instructions: 'Stir-fry chicken with garlic and ginger. Add peppers and soy sauce.',
    calories: 300,
    cuisine: 'Asian',
    dietary: ['High-Protein', 'Low-Calorie'],
    meatType: 'chicken',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 20,
    imageUrl: 'https://www.budgetbytes.com/wp-content/uploads/2024/01/Chicken-Stir-Fry-Pan.jpg',
    rating: 4.5,
    tags: ['easy', 'quick', 'spicy'],
    isFavorite: false,
  ),
  Recipe(
    id: '2',
    title: 'Vegetable Pasta',
    ingredients: ['Pasta', 'Tomatoes', 'Zucchini', 'Olive Oil', 'Garlic', 'Parmesan'],
    instructions: 'Cook pasta and sauté vegetables with garlic. Toss with pasta and top with Parmesan.',
    calories: 450,
    cuisine: 'Italian',
    dietary: ['Vegetarian', 'High-Carb'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-SSJCeuOMHXlN5IlA2oT39G758Ed8p0_OXg&s',
    rating: 4.7,
    tags: ['vegetarian', 'easy', 'healthy'],
    isFavorite: true,
  ),
  Recipe(
    id: '3',
    title: 'Beef Tacos',
    ingredients: ['Ground Beef', 'Taco Shells', 'Lettuce', 'Tomato', 'Cheese', 'Sour Cream'],
    instructions: 'Cook beef and season with taco seasoning. Assemble in taco shells with toppings.',
    calories: 600,
    cuisine: 'Mexican',
    dietary: ['High-Protein'],
    meatType: 'beef',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://www.onceuponachef.com/images/2023/08/Beef-Tacos.jpg',
    rating: 4.2,
    tags: ['quick', 'spicy', 'comfort food'],
    isFavorite: false,
  ),
  Recipe(
    id: '4',
    title: 'Avocado Toast',
    ingredients: ['Bread', 'Avocado', 'Lemon', 'Salt', 'Pepper'],
    instructions: 'Toast the bread, mash avocado with lemon juice, and spread on the toast.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 5,
    cookingTime: 5,
    imageUrl: 'https://www.dinneratthezoo.com/wp-content/uploads/2018/12/avocado-toast-14.jpg',
    rating: 4.8,
    tags: ['vegan', 'easy', 'breakfast'],
    isFavorite: true,
  ),
  Recipe(
    id: '5',
    title: 'Grilled Salmon',
    ingredients: ['Salmon', 'Lemon', 'Garlic', 'Olive Oil', 'Parsley'],
    instructions: 'Grill salmon with garlic, olive oil, and lemon. Serve with a sprinkle of parsley.',
    calories: 500,
    cuisine: 'Mediterranean',
    dietary: ['High-Protein'],
    meatType: 'fish',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://www.allrecipes.com/thmb/CfocX_0yH5_hFxtbFkzoWXrlycs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ALR-12720-grilled-salmon-i-VAT-4x3-888cac0fb8a34f6fbde7bf836850cd1c.jpg',
    rating: 4.6,
    tags: ['healthy', 'quick', 'grilled'],
    isFavorite: false,
  ),
  Recipe(
    id: '6',
    title: 'Pancakes',
    ingredients: ['Flour', 'Eggs', 'Milk', 'Butter', 'Baking Powder'],
    instructions: 'Mix ingredients, pour batter onto the skillet, and cook pancakes on both sides.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 10,
    cookingTime: 10,
    imageUrl: 'https://www.allrecipes.com/thmb/hB7uGW06pqyk6hApOfGxk5kG4SI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/21014-Good-old-Fashioned-Pancakes-mfs_001-1-8fc3e06998fe4fe8b5f2ad6ba7e8ad46.jpg',
    rating: 4.4,
    tags: ['breakfast', 'easy', 'sweet'],
    isFavorite: true,
  ),
  Recipe(
    id: '7',
    title: 'Caesar Salad',
    ingredients: ['Lettuce', 'Croutons', 'Caesar Dressing', 'Parmesan'],
    instructions: 'Toss lettuce with Caesar dressing, top with croutons and Parmesan.',
    calories: 250,
    cuisine: 'Italian',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 5,
    cookingTime: 0,
    imageUrl: 'https://itsavegworldafterall.com/wp-content/uploads/2023/04/Avocado-Caesar-Salad-FI.jpg',
    rating: 4.0,
    tags: ['vegetarian', 'quick', 'healthy'],
    isFavorite: false,
  ),
  Recipe(
    id: '8',
    title: 'Chicken Curry',
    ingredients: ['Chicken', 'Curry Paste', 'Coconut Milk', 'Onion', 'Garlic', 'Rice'],
    instructions: 'Cook chicken and onions, add curry paste and coconut milk, and simmer. Serve with rice.',
    calories: 550,
    cuisine: 'Indian',
    dietary: ['High-Protein'],
    meatType: 'chicken',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 30,
    imageUrl: 'https://www.allrecipes.com/thmb/FL-xnyAllLyHcKdkjUZkotVlHR8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/46822-indian-chicken-curry-ii-DDMFS-4x3-39160aaa95674ee395b9d4609e3b0988.jpg',
    rating: 4.9,
    tags: ['spicy', 'comfort food', 'curry'],
    isFavorite: true,
  ),
  Recipe(
    id: '9',
    title: 'Smoothie Bowl',
    ingredients: ['Frozen Berries', 'Banana', 'Yogurt', 'Granola', 'Honey'],
    instructions: 'Blend frozen berries and banana, top with yogurt, granola, and honey.',
    calories: 300,
    cuisine: 'Healthy',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 10,
    cookingTime: 0,
    imageUrl: 'https://images.immediate.co.uk/production/volatile/sites/30/2022/12/Smoothie-bowl-16df176.jpg',
    rating: 4.6,
    tags: ['vegan', 'healthy', 'breakfast'],
    isFavorite: false,
  ),
  Recipe(
    id: '10',
    title: 'Chocolate Chip Cookies',
    ingredients: ['Flour', 'Butter', 'Sugar', 'Chocolate Chips', 'Eggs'],
    instructions: 'Mix ingredients, shape dough into balls, and bake until golden.',
    calories: 400,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'dessert',
    preparationTime: 15,
    cookingTime: 12,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmv5FKDmnactNtxaIzHqKP_cIirqdDd5NgMg&s',
    rating: 5.0,
    tags: ['sweet', 'baking', 'dessert'],
    isFavorite: true,
  ),
  // Added new recipes from 11 to 20
  Recipe(
    id: '11',
    title: 'Mushroom Risotto',
    ingredients: ['Arborio Rice', 'Mushrooms', 'Onion', 'Parmesan', 'Butter'],
    instructions: 'Sauté mushrooms and onions, add rice and broth, simmer, and finish with Parmesan.',
    calories: 500,
    cuisine: 'Italian',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 30,
    imageUrl: 'https://www.afamilyfeast.com/wp-content/uploads/2012/11/Mushroom-Risotto-3.jpg',
    rating: 4.7,
    tags: ['vegetarian', 'creamy', 'comfort food'],
    isFavorite: false,
  ),
  Recipe(
    id: '12',
    title: 'Shrimp Scampi',
    ingredients: ['Shrimp', 'Garlic', 'Lemon', 'Butter', 'Pasta'],
    instructions: 'Sauté shrimp with garlic and butter, toss with pasta and lemon.',
    calories: 450,
    cuisine: 'Italian',
    dietary: ['High-Protein'],
    meatType: 'seafood',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj5YdYf4Eez99z2iqRJs3AP_Fr51Yypkg9XQ&s',
    rating: 4.8,
    tags: ['seafood', 'garlic', 'pasta'],
    isFavorite: true,
  ),
  Recipe(
    id: '13',
    title: 'BBQ Ribs',
    ingredients: ['Pork Ribs', 'BBQ Sauce', 'Garlic', 'Honey'],
    instructions: 'Grill pork ribs, baste with BBQ sauce and honey, cook until tender.',
    calories: 700,
    cuisine: 'American',
    dietary: ['High-Protein'],
    meatType: 'pork',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 40,
    imageUrl: 'https://www.southernliving.com/thmb/sQ3jAjFAP-SPt_upe-Im4rxMKrQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/oven-baked-baby-back-ribs-beauty-332_preview-34579f7f15ed4548ae3bb5b2048aab60.jpg',
    rating: 4.6,
    tags: ['grilled', 'barbecue', 'meat'],
    isFavorite: false,
  ),
  Recipe(
    id: '14',
    title: 'Eggplant Parmesan',
    ingredients: ['Eggplant', 'Tomato Sauce', 'Parmesan', 'Mozzarella', 'Breadcrumbs'],
    instructions: 'Bread and fry eggplant slices, layer with sauce and cheese, bake until bubbly.',
    calories: 550,
    cuisine: 'Italian',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'dinner',
    preparationTime: 20,
    cookingTime: 30,
    imageUrl: 'https://www.allrecipes.com/thmb/L9wpL6T8bgfo7C09-Euoa-OSN0A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25321-eggplant-parmesan-ii-DDMFS-4x3-6d53ce79765b4c3d9f554d2a47e14d00.jpg',
    rating: 4.3,
    tags: ['vegetarian', 'comfort food', 'baked'],
    isFavorite: false,
  ),
  Recipe(
    id: '15',
    title: 'Falafel',
    ingredients: ['Chickpeas', 'Garlic', 'Parsley', 'Tahini', 'Lemon'],
    instructions: 'Blend ingredients, form into balls, fry until golden brown.',
    calories: 400,
    cuisine: 'Middle Eastern',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 20,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3ifs9JkvcDwpxywlUQRUSZGqKpLbZnd4-Uw&s',
    rating: 4.6,
    tags: ['vegan', 'vegetarian', 'fried'],
    isFavorite: true,
  ),
  Recipe(
    id: '16',
    title: 'Tomato Basil Soup',
    ingredients: ['Tomatoes', 'Basil', 'Cream', 'Garlic', 'Onion'],
    instructions: 'Cook tomatoes and onions with garlic, blend, and finish with basil and cream.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 15,
    cookingTime: 30,
    imageUrl: 'https://www.cubesnjuliennes.com/wp-content/uploads/2022/09/Tomato-Basil-Soup-Recipe.jpg',
    rating: 4.2,
    tags: ['comfort food', 'vegetarian', 'soups'],
    isFavorite: false,
  ),
  Recipe(
    id: '17',
    title: 'Lentil Stew',
    ingredients: ['Lentils', 'Carrots', 'Celery', 'Tomatoes', 'Garlic'],
    instructions: 'Simmer lentils and vegetables in broth until tender.',
    calories: 400,
    cuisine: 'American',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 40,
    imageUrl: 'https://www.simplyrecipes.com/thmb/jsHWnVBqXlGm-Akgw-qIC0gkqTg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2010__01__lentil-stew-sausage-horiz-a-1200-023475d5030e4d1fae01f5d98ed7015e.jpg',
    rating: 4.4,
    tags: ['vegan', 'healthy', 'stews'],
    isFavorite: false,
  ),
  Recipe(
    id: '18',
    title: 'Chicken Fajitas',
    ingredients: ['Chicken', 'Bell Peppers', 'Onions', 'Tortillas', 'Sour Cream'],
    instructions: 'Cook chicken and vegetables, serve with tortillas and toppings.',
    calories: 500,
    cuisine: 'Mexican',
    dietary: ['High-Protein'],
    meatType: 'chicken',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 20,
    imageUrl: 'https://www.simplyrecipes.com/thmb/Igb2OthIr1Onu0tCPyNVMp8EmtI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2015__04__chicken-fajitas-horiz-a2-1800-8ca8b1b6a694468b8bccf5a1d8e07c6d.jpg',
    rating: 4.8,
    tags: ['spicy', 'comfort food', 'mexican'],
    isFavorite: true,
  ),
  Recipe(
    id: '19',
    title: 'Grilled Cheese Sandwich',
    ingredients: ['Bread', 'Cheese', 'Butter'],
    instructions: 'Grill bread with butter and melted cheese until golden brown.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 5,
    cookingTime: 5,
    imageUrl: 'https://cdn.loveandlemons.com/wp-content/uploads/2023/01/grilled-cheese.jpg',
    rating: 4.5,
    tags: ['comfort food', 'quick', 'cheese'],
    isFavorite: true,
  ),
  Recipe(
    id: '20',
    title: 'Fruit Salad',
    ingredients: ['Apple', 'Banana', 'Strawberries', 'Orange', 'Lemon'],
    instructions: 'Chop fruits and toss with lemon juice.',
    calories: 200,
    cuisine: 'Healthy',
    dietary: ['Vegan', 'Gluten-Free'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 10,
    cookingTime: 0,
    imageUrl: 'https://www.cubesnjuliennes.com/wp-content/uploads/2022/06/Fresh-Summer-Fruit-Salad-Recipe.jpg',
    rating: 4.1,
    tags: ['healthy', 'vegan', 'refreshing'],
    isFavorite: false,
  ),
];
