class Recipe {
  final String id;
  final String title;
  final List<String> ingredients;
  final String instructions;
  final int calories;
  final String cuisine;
  final List<String> dietary;
  final String meatType;
  final String mealType;
  final int preparationTime; // Added preparation time
  final int cookingTime; // Added cooking time
  final String imageUrl; // Added image URL
  final double rating; // Added rating
  final List<String> tags; // Added tags for categorizing recipes
  final bool isFavorite; // Added favorite status

  Recipe({
    required this.id,
    required this.title,
    required this.ingredients,
    required this.instructions,
    required this.calories,
    required this.cuisine,
    required this.dietary,
    required this.meatType,
    required this.mealType,
    required this.preparationTime,
    required this.cookingTime,
    required this.imageUrl,
    required this.rating,
    required this.tags,
    required this.isFavorite,
  });
}

List<Recipe> recipes = [
  Recipe(
    id: '1',
    title: 'Chicken Stir Fry',
    ingredients: ['Chicken', 'Bell Peppers', 'Soy Sauce', 'Garlic', 'Ginger'],
    instructions: 'Stir-fry chicken with garlic and ginger. Add peppers and soy sauce.',
    calories: 300,
    cuisine: 'Asian',
    dietary: ['High-Protein', 'Low-Calorie'],
    meatType: 'chicken',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 20,
    imageUrl: 'https://example.com/chicken_stir_fry.jpg',
    rating: 4.5,
    tags: ['easy', 'quick', 'spicy'],
    isFavorite: false,
  ),
  Recipe(
    id: '2',
    title: 'Vegetable Pasta',
    ingredients: ['Pasta', 'Tomatoes', 'Zucchini', 'Olive Oil', 'Garlic', 'Parmesan'],
    instructions: 'Cook pasta and sauté vegetables with garlic. Toss with pasta and top with Parmesan.',
    calories: 450,
    cuisine: 'Italian',
    dietary: ['Vegetarian', 'High-Carb'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://example.com/vegetable_pasta.jpg',
    rating: 4.7,
    tags: ['vegetarian', 'easy', 'healthy'],
    isFavorite: true,
  ),
  Recipe(
    id: '3',
    title: 'Beef Tacos',
    ingredients: ['Ground Beef', 'Taco Shells', 'Lettuce', 'Tomato', 'Cheese', 'Sour Cream'],
    instructions: 'Cook beef and season with taco seasoning. Assemble in taco shells with toppings.',
    calories: 600,
    cuisine: 'Mexican',
    dietary: ['High-Protein'],
    meatType: 'beef',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://example.com/beef_tacos.jpg',
    rating: 4.2,
    tags: ['quick', 'spicy', 'comfort food'],
    isFavorite: false,
  ),
  Recipe(
    id: '4',
    title: 'Avocado Toast',
    ingredients: ['Bread', 'Avocado', 'Lemon', 'Salt', 'Pepper'],
    instructions: 'Toast the bread, mash avocado with lemon juice, and spread on the toast.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 5,
    cookingTime: 5,
    imageUrl: 'https://example.com/avocado_toast.jpg',
    rating: 4.8,
    tags: ['vegan', 'easy', 'breakfast'],
    isFavorite: true,
  ),
  Recipe(
    id: '5',
    title: 'Grilled Salmon',
    ingredients: ['Salmon', 'Lemon', 'Garlic', 'Olive Oil', 'Parsley'],
    instructions: 'Grill salmon with garlic, olive oil, and lemon. Serve with a sprinkle of parsley.',
    calories: 500,
    cuisine: 'Mediterranean',
    dietary: ['High-Protein'],
    meatType: 'fish',
    mealType: 'dinner',
    preparationTime: 10,
    cookingTime: 15,
    imageUrl: 'https://example.com/grilled_salmon.jpg',
    rating: 4.6,
    tags: ['healthy', 'quick', 'grilled'],
    isFavorite: false,
  ),
  Recipe(
    id: '6',
    title: 'Pancakes',
    ingredients: ['Flour', 'Eggs', 'Milk', 'Butter', 'Baking Powder'],
    instructions: 'Mix ingredients, pour batter onto the skillet, and cook pancakes on both sides.',
    calories: 350,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 10,
    cookingTime: 10,
    imageUrl: 'https://example.com/pancakes.jpg',
    rating: 4.4,
    tags: ['breakfast', 'easy', 'sweet'],
    isFavorite: true,
  ),
  Recipe(
    id: '7',
    title: 'Caesar Salad',
    ingredients: ['Lettuce', 'Croutons', 'Caesar Dressing', 'Parmesan'],
    instructions: 'Toss lettuce with Caesar dressing, top with croutons and Parmesan.',
    calories: 250,
    cuisine: 'Italian',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'lunch',
    preparationTime: 5,
    cookingTime: 0,
    imageUrl: 'https://example.com/caesar_salad.jpg',
    rating: 4.0,
    tags: ['vegetarian', 'quick', 'healthy'],
    isFavorite: false,
  ),
  Recipe(
    id: '8',
    title: 'Chicken Curry',
    ingredients: ['Chicken', 'Curry Paste', 'Coconut Milk', 'Onion', 'Garlic', 'Rice'],
    instructions: 'Cook chicken and onions, add curry paste and coconut milk, and simmer. Serve with rice.',
    calories: 550,
    cuisine: 'Indian',
    dietary: ['High-Protein'],
    meatType: 'chicken',
    mealType: 'dinner',
    preparationTime: 15,
    cookingTime: 30,
    imageUrl: 'https://example.com/chicken_curry.jpg',
    rating: 4.9,
    tags: ['spicy', 'comfort food', 'curry'],
    isFavorite: true,
  ),
  Recipe(
    id: '9',
    title: 'Smoothie Bowl',
    ingredients: ['Frozen Berries', 'Banana', 'Yogurt', 'Granola', 'Honey'],
    instructions: 'Blend frozen berries and banana, top with yogurt, granola, and honey.',
    calories: 300,
    cuisine: 'Healthy',
    dietary: ['Vegetarian', 'Vegan'],
    meatType: 'none',
    mealType: 'breakfast',
    preparationTime: 10,
    cookingTime: 0,
    imageUrl: 'https://example.com/smoothie_bowl.jpg',
    rating: 4.6,
    tags: ['vegan', 'healthy', 'breakfast'],
    isFavorite: false,
  ),
  Recipe(
    id: '10',
    title: 'Chocolate Chip Cookies',
    ingredients: ['Flour', 'Butter', 'Sugar', 'Chocolate Chips', 'Eggs'],
    instructions: 'Mix ingredients, shape dough into balls, and bake until golden.',
    calories: 400,
    cuisine: 'American',
    dietary: ['Vegetarian'],
    meatType: 'none',
    mealType: 'dessert',
    preparationTime: 15,
    cookingTime: 12,
    imageUrl: 'https://example.com/chocolate_chip_cookies.jpg',
    rating: 5.0,
    tags: ['sweet', 'baking', 'dessert'],
    isFavorite: true,
  ),
];

